on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          check-latest: false
          cache: maven

      - name: Create jar with dependencies
        run: mvn package -Pjar-build -DskipTests

      # ${{ github.ref_name }} # or GITHUB_REF_NAME - current tag
      - name: Package to RPM
        run: rpmbuild -bb --build-in-place packaging/rpm/artipie.spec

      - run: rpmlint /home/runner/rpmbuild/RPMS/noarch/artipie*.rpm

      - run: yum install -y /home/runner/rpmbuild/RPMS/noarch/artipie*.rpm

      - run: repoquery -l artipie
